#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DVI-D-1 -d I II III
bspc monitor DP-2 -d IV V VI
bspc monitor HDMI-2 -d VII VIII IX


#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"


# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
xrandr --output DVI-D-1 --mode 1920x1080 --pos 0x300 --rotate normal --output DP-2 --mode 2560x1440 --pos 1920x0 --rotate normal --output HDMI-2 --mode 1680x1050 --pos 4480x250 --rotate normal &
compton -b --respect-prop-shadow --config /home/neo/.config/picom.conf &
feh --bg-scale /usr/share/wallpapers/feh/910936.jpg &
wmname compiz &
dunst &
/home/neo/.config/polybar/launch-bspwm.sh &
xss-lock /home/neo/.config/i3/lock.sh &
